version: '2'

services:
  bdmerdb:
    hostname: dbmerdb
    image: couchdb:latest
    volumes:
      - ./.docker/couchdb_data/data:/usr/local/var/lib/couchdb
      - ./.docker/couchdb_data/config/local.d:/usr/local/etc/couchdb/local.d
    ports:
      - "5984:5984"
    networks:
      - bdmer-network

  bdmer:
    hostname: dbmer
    build:
      context: .
      dockerfile: ./.docker/angular-seed.development.dockerfile
    command: npm start
    container_name: bdmer3-start
    image: bdmer3
    networks:
      - bdmer-network
    ports:
      - '5555:5555'
    links:
      - bdmerdb

networks:
  bdmer-network:
    driver: bridge
